### ISSUE TITLE
تغییر جزئی فایل ReadMe

### ISSUE THREAD

**Issue by omidgolparvar** [cedarstudios/cedarmaps-ios-sdk#1]
<div dir='rtl'>
سلام.
توی فایل Readme بیان شده که :

<pre dir='ltr'>
CedarMaps SDK is based on Mapbox iOS SDK v4.0 and ...
</pre>

با توجه به اینکه الان نسخه مورد استفاده رو برابر ۵ قرار دادین، این قسمت از فایل رو هم تصحیح کنین. 

گودلاک.
تنکیو.

</div>

**Comment by ghost** [comment]
Done.
